language: python
python:
  - "3.6.3"
  - "3.6.4"
# command to install dependencies
install:
  - python setup.py install
  - pip install coverage codecov flake8 mypy
# command to run tests
script:
  - src/scripts/run-tests.sh
after_success:
  - codecov
# blocklist
branches:
  except:
    conda-recipe
